// <auto-generated />
using System;
using GameServer.Persistence.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameServer.Persistence.Postgres.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260525134938_InitialTenantSchema")]
    partial class InitialTenantSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameServer.Persistence.Postgres.GameRecord", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("text");

                    b.Property<int>("CurrentSchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GameId");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("GameServer.Persistence.Postgres.GameVersionRecord", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("text");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GameId", "SchemaVersion");

                    b.ToTable("game_versions", (string)null);
                });

            modelBuilder.Entity("GameServer.Persistence.Postgres.RoomEventRecord", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text");

                    b.Property<long>("Tick")
                        .HasColumnType("bigint");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoomId", "Tick", "Ordinal");

                    b.ToTable("room_events", (string)null);
                });

            modelBuilder.Entity("GameServer.Persistence.Postgres.RoomRecord", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GameSchemaVersion")
                        .HasColumnType("integer");

                    b.HasKey("RoomId");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("GameServer.Persistence.Postgres.RoomSnapshotRecord", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text");

                    b.Property<int>("GameSchemaVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<byte[]>("State")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("Tick")
                        .HasColumnType("bigint");

                    b.HasKey("RoomId");

                    b.ToTable("room_snapshots", (string)null);
                });

            modelBuilder.Entity("GameServer.Persistence.Postgres.SessionRecord", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SessionId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("GameServer.Persistence.Postgres.TenantAuditRecord", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AuditId");

                    b.ToTable("audit_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
