using System.Linq;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Xunit;

namespace Citadel.RepoAnalyzers.Tests;

public sealed class CoLocatedTestAnalyzerTests
{
    [Fact]
    public async Task Reports_When_ProductionFile_HasNoCoLocatedTest()
    {
        var diagnostics = await new AnalyzerScenario()
            .Production("/repo/src/Feature/Thing.cs")
            .RunAsync();

        var diagnostic = Assert.Single(diagnostics);
        Assert.Equal(CoLocatedTestAnalyzer.DiagnosticId, diagnostic.Id);
        var message = diagnostic.GetMessage();
        Assert.Contains("Thing.cs", message);
        Assert.Contains("Thing.Tests.cs", message);
    }

    [Fact]
    public async Task DoesNotReport_When_CoLocatedTestExists()
    {
        var diagnostics = await new AnalyzerScenario()
            .Production("/repo/src/Feature/Thing.cs")
            .ExistingTestFile("/repo/src/Feature/Thing.Tests.cs")
            .RunAsync();

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task Ignores_TestFiles_Themselves()
    {
        var diagnostics = await new AnalyzerScenario()
            .Production("/repo/src/Feature/Thing.Tests.cs")
            .RunAsync();

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task Ignores_FakesFiles()
    {
        var diagnostics = await new AnalyzerScenario()
            .Production("/repo/src/Feature/Thing.Fakes.cs")
            .RunAsync();

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task Ignores_FilesUnderTestingFolder()
    {
        var diagnostics = await new AnalyzerScenario()
            .Production("/repo/src/Feature/Testing/SharedHarness.cs")
            .RunAsync();

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task Ignores_GeneratedFiles_WhenConfigured()
    {
        // Default config has ignoredGeneratedFiles = true; ".g.cs" is a generated marker.
        var byName = await new AnalyzerScenario()
            .Production("/repo/src/Feature/Widget.g.cs")
            .RunAsync();
        Assert.Empty(byName);

        // Also covers header-based detection.
        var byHeader = await new AnalyzerScenario()
            .Production("/repo/src/Feature/Widget.cs", "// <auto-generated/>\nclass Widget {}")
            .RunAsync();
        Assert.Empty(byHeader);
    }

    [Fact]
    public async Task GeneratedFiles_AreReported_WhenIgnoreDisabled()
    {
        const string config = """
        { "ignoredGeneratedFiles": false }
        """;

        var diagnostics = await new AnalyzerScenario()
            .Production("/repo/src/Feature/Widget.g.cs")
            .Config(config)
            .RunAsync();

        Assert.Single(diagnostics);
    }

    [Fact]
    public async Task Respects_IgnoredFileSuffixes_FromConfig()
    {
        const string config = """
        { "ignoredFileSuffixes": [".Custom.cs"] }
        """;

        var diagnostics = await new AnalyzerScenario()
            .Production("/repo/src/Feature/Thing.Custom.cs")
            .Config(config)
            .RunAsync();

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task Respects_IgnoredPathGlobs_FromConfig()
    {
        const string config = """
        { "ignoredPathGlobs": ["**/Generated/**"] }
        """;

        var diagnostics = await new AnalyzerScenario()
            .Production("/repo/src/Feature/Generated/Thing.cs")
            .Config(config)
            .RunAsync();

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task Respects_RequiredTestSuffix_FromConfig()
    {
        const string config = """
        { "requiredTestSuffix": ".Spec.cs" }
        """;

        // A ".Tests.cs" sibling no longer satisfies the rule when the suffix is ".Spec.cs".
        var withTests = await new AnalyzerScenario()
            .Production("/repo/src/Feature/Thing.cs")
            .ExistingTestFile("/repo/src/Feature/Thing.Tests.cs")
            .Config(config)
            .RunAsync();
        var diagnostic = Assert.Single(withTests);
        Assert.Contains("Thing.Spec.cs", diagnostic.GetMessage());

        // The ".Spec.cs" sibling satisfies it.
        var withSpec = await new AnalyzerScenario()
            .Production("/repo/src/Feature/Thing.cs")
            .ExistingTestFile("/repo/src/Feature/Thing.Spec.cs")
            .Config(config)
            .RunAsync();
        Assert.Empty(withSpec);
    }
}
